# PANDAS

In [71]:
# import library

import pandas as pd

### 1. Load File

In [38]:
# read data

df = pd.read_csv(r"C:\Users\thumb\Downloads\student_data.csv")
# “Treat backslashes (\) as literal characters, not as special escape characters.”

In [39]:
df

,study_hours,attendance,previous_grade,sleep_hours,extracurricular,tutoring,pass
0,33,83,40,6.024681,13,No,0
1,19,51,92,9.397884,1,Yes,0
2,12,81,93,7.645331,10,Yes,1
3,25,72,93,5.466119,0,No,1
4,23,71,42,6.989486,18,No,1
...,...,...,...,...,...,...,...
295,18,90,88,6.965643,9,No,1
296,16,98,83,7.439766,0,Yes,1
297,27,63,58,9.028642,17,No,1
298,19,64,81,6.426289,17,No,1
299,32,80,80,8.625468,13,Yes,1

### 2. Inspection Of The Data

In [40]:
df.head()   # show the first 5 rows of the data

,study_hours,attendance,previous_grade,sleep_hours,extracurricular,tutoring,pass
0,33,83,40,6.024681,13,No,0
1,19,51,92,9.397884,1,Yes,0
2,12,81,93,7.645331,10,Yes,1
3,25,72,93,5.466119,0,No,1
4,23,71,42,6.989486,18,No,1

In [41]:
df.tail()   # show the last 5 rows of the data

,study_hours,attendance,previous_grade,sleep_hours,extracurricular,tutoring,pass
295,18,90,88,6.965643,9,No,1
296,16,98,83,7.439766,0,Yes,1
297,27,63,58,9.028642,17,No,1
298,19,64,81,6.426289,17,No,1
299,32,80,80,8.625468,13,Yes,1

In [42]:
df.shape   # show the number of rows and columns in the data

(300, 7)

In [43]:
df.columns   # show the column names in the data

Index(['study_hours', 'attendance', 'previous_grade', 'sleep_hours',
       'extracurricular', 'tutoring', 'pass'],
      dtype='object')

In [44]:
df.index   # show the index of the data

RangeIndex(start=0, stop=300, step=1)

In [45]:
df.info()   # show the data types of each column and the number of non-null values in each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   study_hours      300 non-null    int64
 1   attendance       300 non-null    int64
 2   previous_grade   300 non-null    int64
 3   sleep_hours      300 non-null    float64
 4   extracurricular  300 non-null    int64
 5   tutoring         300 non-null    object
 6   pass             300 non-null    int64
dtypes: float64(1), int64(5), object(1)
memory usage: 16.5+ KB

In [46]:
df.describe()   # show the summary statistics of the numerical columns in the data, such as count, mean, std, min, 25%, 50%, 75%, and max. It will only show the numerical columns by default. If you want to include all columns, you can use df.describe(include='all').

,study_hours,attendance,previous_grade,sleep_hours,extracurricular,pass
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,22.880000,75.380000,66.893333,7.139780,9.443333,0.583333
std,10.603161,14.219808,16.157729,1.658102,5.596235,0.493830
min,5.000000,50.000000,40.000000,4.016265,0.000000,0.000000
25%,13.000000,63.000000,53.000000,5.844110,4.000000,0.000000
50%,24.000000,75.000000,66.000000,7.210319,10.000000,1.000000
75%,32.000000,87.000000,81.250000,8.543893,14.000000,1.000000
max,39.000000,99.000000,94.000000,9.986156,19.000000,1.000000

### 3. Data Selection

In [47]:
# using names

In [48]:
# df.loc[row_label, column_label]

df.loc[0:1,'study_hours':'attendance']  # show the first 2 rows and the columns from 'study_hours' to 'attendance' of the data. And the index starts from 0, so we use 0:1 to show the first 2 rows and 'study_hours':'attendance' to show the columns from 'study_hours' to 'attendance'.

   study_hours  attendance
0           33          83
1           19          51

In [49]:
# using index

In [50]:
df.iloc[0:5, 0:3]   # show the first 5 rows and the first 3 columns of the data. And the index starts from 0, so we use 0:5 to show the first 5 rows and 0:3 to show the first 3 columns.

   study_hours  attendance  previous_grade
0           33          83              40
1           19          51              92
2           12          81              93
3           25          72              93
4           23          71              42

### 4. Handling Missing Values or Null Values (Data Cleaning)

In [51]:
# checking for missing values or null values

df.isnull()   # show the missing values in the data. It will return a DataFrame of the same shape as the original DataFrame, with True for missing values and False for non-missing values.

,study_hours,attendance,previous_grade,sleep_hours,extracurricular,tutoring,pass
0,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...
295,False,False,False,False,False,False,False
296,False,False,False,False,False,False,False
297,False,False,False,False,False,False,False
298,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False

In [52]:
# using sum() to count the number of missing values in each column

df.isnull().sum()   # show the number of missing values in each column of the data. It will return a Series with the column names as the index and the number of missing values as the values.

study_hours        0
attendance         0
previous_grade     0
sleep_hours        0
extracurricular    0
tutoring           0
pass               0
dtype: int64

In [53]:
# dropping null values

df.dropna()   # drop the rows with missing values in the data. It will return a new DataFrame with the rows with missing values dropped. The original DataFrame will not be modified.

,study_hours,attendance,previous_grade,sleep_hours,extracurricular,tutoring,pass
0,33,83,40,6.024681,13,No,0
1,19,51,92,9.397884,1,Yes,0
2,12,81,93,7.645331,10,Yes,1
3,25,72,93,5.466119,0,No,1
4,23,71,42,6.989486,18,No,1
...,...,...,...,...,...,...,...
295,18,90,88,6.965643,9,No,1
296,16,98,83,7.439766,0,Yes,1
297,27,63,58,9.028642,17,No,1
298,19,64,81,6.426289,17,No,1
299,32,80,80,8.625468,13,Yes,1

In [54]:
# filling null values

df.fillna(0)   # fill the missing values in the data with 0. It will return a new DataFrame with the missing values filled with 0. The original DataFrame will not be modified.

,study_hours,attendance,previous_grade,sleep_hours,extracurricular,tutoring,pass
0,33,83,40,6.024681,13,No,0
1,19,51,92,9.397884,1,Yes,0
2,12,81,93,7.645331,10,Yes,1
3,25,72,93,5.466119,0,No,1
4,23,71,42,6.989486,18,No,1
...,...,...,...,...,...,...,...
295,18,90,88,6.965643,9,No,1
296,16,98,83,7.439766,0,Yes,1
297,27,63,58,9.028642,17,No,1
298,19,64,81,6.426289,17,No,1
299,32,80,80,8.625468,13,Yes,1

### 5. Data Type Conversion

In [55]:
# changing data types

df['previous_grade'].astype('float')   # convert the data type of the 'previous_grade' column to float. It will return a new Series with the data type of float. The original Series will not be modified.

0      40.0
1      92.0
2      93.0
3      93.0
4      42.0
       ...
295    88.0
296    83.0
297    58.0
298    81.0
299    80.0
Name: previous_grade, Length: 300, dtype: float64

In [56]:
### 6. Remove Duplicates

df.drop_duplicates()   # remove duplicate rows from the data. It will return a new DataFrame with the duplicate rows removed. The original DataFrame will not be modified.

,study_hours,attendance,previous_grade,sleep_hours,extracurricular,tutoring,pass
0,33,83,40,6.024681,13,No,0
1,19,51,92,9.397884,1,Yes,0
2,12,81,93,7.645331,10,Yes,1
3,25,72,93,5.466119,0,No,1
4,23,71,42,6.989486,18,No,1
...,...,...,...,...,...,...,...
295,18,90,88,6.965643,9,No,1
296,16,98,83,7.439766,0,Yes,1
297,27,63,58,9.028642,17,No,1
298,19,64,81,6.426289,17,No,1
299,32,80,80,8.625468,13,Yes,1

### 6. Data Transformation and Analysis

In [57]:
# sorting data

df.sort_values(by='study_hours')   # sort the data by the 'study_hours' column in ascending order. It will return a new DataFrame sorted by the 'study_hours' column. The original DataFrame will not be modified.

,study_hours,attendance,previous_grade,sleep_hours,extracurricular,tutoring,pass
292,5,69,86,8.393107,16,No,0
199,5,61,89,7.749856,4,No,1
66,5,77,64,9.558697,5,Yes,1
187,5,68,55,6.753934,2,No,0
71,5,95,72,8.503012,8,No,0
...,...,...,...,...,...,...,...
223,39,66,65,5.523331,15,No,1
217,39,67,88,8.804499,7,No,1
204,39,65,57,8.284355,8,Yes,0
252,39,68,46,8.950644,6,Yes,0
262,39,62,74,8.678553,3,Yes,1

In [58]:
# accending order

df.sort_values(by='study_hours', ascending=True)   # sort the data by the 'study_hours' column in ascending order. It will return a new DataFrame sorted by the 'study_hours' column. The original DataFrame will not be modified.

,study_hours,attendance,previous_grade,sleep_hours,extracurricular,tutoring,pass
292,5,69,86,8.393107,16,No,0
199,5,61,89,7.749856,4,No,1
66,5,77,64,9.558697,5,Yes,1
187,5,68,55,6.753934,2,No,0
71,5,95,72,8.503012,8,No,0
...,...,...,...,...,...,...,...
223,39,66,65,5.523331,15,No,1
217,39,67,88,8.804499,7,No,1
204,39,65,57,8.284355,8,Yes,0
252,39,68,46,8.950644,6,Yes,0
262,39,62,74,8.678553,3,Yes,1

In [59]:
# decending order

df.sort_values(by='study_hours', ascending=False)   # sort the data by the 'study_hours' column in descending order. It will return a new DataFrame sorted by the 'study_hours' column. The original DataFrame will not be modified.

,study_hours,attendance,previous_grade,sleep_hours,extracurricular,tutoring,pass
258,39,68,86,6.176547,9,No,1
262,39,62,74,8.678553,3,Yes,1
215,39,92,85,9.384582,14,Yes,1
252,39,68,46,8.950644,6,Yes,0
78,39,70,94,5.897179,6,No,1
...,...,...,...,...,...,...,...
130,5,72,62,5.364106,11,No,1
71,5,95,72,8.503012,8,No,0
94,5,54,58,6.589169,16,No,0
98,5,73,48,5.000385,12,Yes,0
66,5,77,64,9.558697,5,Yes,1

In [60]:
# sorting by multiple columns

df.sort_values(by=['study_hours', 'previous_grade'], ascending=[True, False])   # sort the data by the 'study_hours' column in ascending order and then by the 'previous_grade' column in descending order. It will return a new DataFrame sorted by the 'study_hours' column and then by the 'previous_grade' column. The original DataFrame will not be modified.

,study_hours,attendance,previous_grade,sleep_hours,extracurricular,tutoring,pass
199,5,61,89,7.749856,4,No,1
292,5,69,86,8.393107,16,No,0
71,5,95,72,8.503012,8,No,0
66,5,77,64,9.558697,5,Yes,1
130,5,72,62,5.364106,11,No,1
...,...,...,...,...,...,...,...
286,39,70,57,6.984789,4,Yes,1
95,39,94,56,5.996895,13,No,1
40,39,72,52,4.523741,6,No,0
93,39,50,49,7.257096,6,Yes,0
252,39,68,46,8.950644,6,Yes,0

In [61]:
# value counts

df['tutoring'].value_counts()   # show the count of unique values in the 'tutoring' column. It will return a Series with the unique values as the index and the count of each unique value as the values.

tutoring
No     152
Yes    148
Name: count, dtype: int64

In [62]:
df['pass'].value_counts()   # show the count of unique values in the 'pass' column. It will return a Series with the unique values as the index and the count of each unique value as the values.

pass
1    175
0    125
Name: count, dtype: int64

In [63]:
# grouping data

df.groupby('tutoring')['study_hours'].mean()   # group the data by the 'tutoring' column and calculate the mean of the 'study_hours' column for each group. It will return a Series with the unique values in the 'tutoring' column as the index and the mean of the 'study_hours' column for each group as the values.

tutoring
No     22.539474
Yes    23.229730
Name: study_hours, dtype: float64

In [64]:
# Feature Engineering

df['total_study_time'] = df['study_hours'] + df['attendance']   # create a new column 'total_study_time' by adding the 'study_hours' and 'attendance' columns. It will return a new Series with the total study time for each row. The original DataFrame will be modified to include the new column.

In [65]:
df['good_students'] = 'No'  # create a new column 'good_students' and set the default value to 'No'. It will return a new Series with the value 'No' for each row. The original DataFrame will be modified to include the new column.
df.loc[(df['study_hours'] > 30 ) & (df['attendance'] > 70), 'good_students'] = 'Yes'    # update the 'good_students' column to 'Yes' for the rows where the 'study_hours' is greater than 30 and the 'attendance' is greater than 70. It will return a new Series with the updated values for the 'good_students' column. The original DataFrame will be modified to include the updated values in the 'good_students' column.

In [66]:
df['good_students'].value_counts()  # show the count of unique values in the 'good_students' column. It will return a Series with the unique values as the index and the count of each unique value as the values.

good_students
No     254
Yes     46
Name: count, dtype: int64

### Pivot Table

In [ ]:
# index
# columns
# values

pd.pivot_table(data = df, index= ["tutoring"], columns= ["pass"], values= ["previous_grade"])

         previous_grade
pass                  0          1
tutoring
No            59.419355  69.655556
Yes           57.857143  76.117647

### Merging DataFrames

In [86]:
# create 2 data frames

students = pd.DataFrame({
    'student_id': [101, 102, 103, 104],
    'name': ['Ramesh', 'Suresh', 'Mahesh', 'Naresh'],
    'city': ['Hyderabad', 'Vijayawada', 'Guntur', 'Nellore']
})

marks = pd.DataFrame({
    'student_id': [101, 102, 102, 105],
    'subject': ['Maths', 'Maths', 'Science', 'Maths'],
    'marks': [85, 78, 88, 90]
})

In [87]:
students.head()

   student_id    name        city
0         101  Ramesh   Hyderabad
1         102  Suresh  Vijayawada
2         103  Mahesh      Guntur
3         104  Naresh     Nellore

In [88]:
marks.head()

   student_id  subject  marks
0         101    Maths     85
1         102    Maths     78
2         102  Science     88
3         105    Maths     90

In [92]:
# inner (common)

inner_merged_df = pd.merge(students, marks, on= 'student_id', how= 'inner')

In [94]:
inner_merged_df

   student_id    name        city  subject  marks
0         101  Ramesh   Hyderabad    Maths     85
1         102  Suresh  Vijayawada    Maths     78
2         102  Suresh  Vijayawada  Science     88

In [93]:
# outer (union)

outer_merged_df = pd.merge(students, marks, on= 'student_id', how= 'outer')

In [95]:
outer_merged_df

   student_id    name        city  subject  marks
0         101  Ramesh   Hyderabad    Maths   85.0
1         102  Suresh  Vijayawada    Maths   78.0
2         102  Suresh  Vijayawada  Science   88.0
3         103  Mahesh      Guntur      NaN    NaN
4         104  Naresh     Nellore      NaN    NaN
5         105     NaN         NaN    Maths   90.0

### Exporting Dataset

In [98]:
inner_merged_df.to_csv(r"C:\Users\thumb\Downloads\inner_merged_df.csv")

In [99]:
outer_merged_df.to_csv(r"C:\Users\thumb\Downloads\outer_merged_df.csv")